a = int(input())
b = int(input())
c = int(input())
d = int(input())
rook = (a == c or b == d)
bishop = (abs(a - c) == abs(b - d))
king = (max(abs(a - c), abs(b - d)) == 1)
queen = rook or bishop
pawn_move = (c == a and (d - b == 1 or (b == 2 and d - b == 2)))
pawn_attack = (abs(c - a) == 1 and d - b == 1)
print(rook)
print(bishop)
print(king)
print(queen)
print(pawn_move, pawn_attack)
